fix shaker-spot execution
A previous commit introduced a feature to specify the directory the
agent uses for shell class execution via a cfg entry, agent_dir.

However this addition introduced an error when using shaker-spot:
  oslo_config.cfg.NoSuchOptError: no such option agent_dir in group
  [DEFAULT]

This commit fixes shaker-spot while still supporting the agent_dir
feature

Change-Id: I7cfb87ba406e177121e7914225857937a19502e4